#!/usr/bin/expect -f

################## Инструкция ######################################

## Использовать:

# eltex 10.0.0.1 1/1/1:1

## Как создать короткий alias: 
## Убираете # и правите расположение файла, а далее копируете и вставляйте в терминал

# cat >> ~/.bash_aliases << EOF
# alias eltex='<расположение файла>/eltex.sh telnet'
# EOF

# chmod 700 <расположение файла>/eltex.sh - дать права на выполнение

# source ./.bashrc - перечитать фаил с alias

####################################################################

# Проверяем количество аргументов
if {$argc < 2} {
    puts "Usage: $argv0 <HOST> <USER_PORT>"
    exit 1
}

set HOST [lindex $argv 0]
set USER_PORT [lindex $argv 1]
set DELAY 1
set timeout 10

# Если хотите захардкодить, напишите: set USER "admin"
set USER $env(USER)
set PASS $env(PASS)

spawn telnet $HOST

expect {
    "User" { send "$USER\r"; exp_continue }
    "Password:" { send "$PASS\r" }
    timeout { puts "Нет ответа по таймауту"; exit 1 }
}

expect -re {[#>]$}

# Список команд
set commands [list \
    "terminal datadump" \
    "show interfaces status $USER_PORT" \
    "show running-config interfaces $USER_PORT" \
    "show interfaces counters $USER_PORT" \
    "no terminal datadump" \
    "show mac address-table interface $USER_PORT" \
    "show logging | include $USER_PORT" \
    ]

foreach cmd $commands {
    send "$cmd\r"
    expect -re {[#>]$}
    sleep $DELAY
}

interact
