#!/usr/bin/expect -f

################## Инструкция ######################################

## Использовать:

# ltp 10.0.0.1 1/1/1:1

## Как создать короткий alias: 
## Убираете # и правите расположение файла, а далее копируете и вставляйте в терминал

# cat >> ~/.bash_aliases << EOF
# alias ltp='<расположение файла>/ltp.sh telnet'
# EOF

# chmod 700 <расположение файла>/ltp.sh - дать права на выполнение

# source ./.bashrc - перечитать фаил с alias

####################################################################

# Проверяем количество аргументов
if {$argc < 2} {
    puts "Usage: $argv0 <HOST> <USER_PORT>"
    exit 1
}

set HOST [lindex $argv 0]
set USER_PORT [lindex $argv 1]
set DELAY 1

# Если хотите захардкодить, напишите: set USER "admin"
set USER $env(USER)
set PASS $env(PASS)
set timeout 10

spawn telnet $HOST

expect {
    "login" { send "$USER\r"; exp_continue }
    "Password:" { send "$PASS\r" }
    timeout { puts "Нет ответа по таймауту"; exit 1 }
}

expect -re {[#>]$}

# Список команд
set commands [list \
    "show interface ont $USER_PORT state" \
    "show interface ont $USER_PORT ports" \
    "show mac interface ont $USER_PORT" \
    "show interface ont $USER_PORT connections" \
    "show interface ont $USER_PORT laser" \
]

foreach cmd $commands {
    send "$cmd\r"
    expect -re {[#>]$}
    sleep $DELAY
}

interact
