#!/usr/bin/expect -f

################## Инструкция ######################################

## Использовать:

# zte320 10.0.0.1 1/1/1:1

## Как создать короткий alias: 
## Убираете # и правите расположение файла, а далее копируете и вставляйте в терминал

# cat >> ~/.bash_aliases << EOF
# alias zte320='<расположение файла>/zte320.exp telnet'
# EOF

# chmod 700 <расположение файла>/zte320.exp - дать права на выполнение

# source ./.bashrc - перечитать фаил с alias

####################################################################

# Проверяем аргументы
if {$argc < 2} {
    puts "Usage: $argv0 <HOST> <USER_PORT>"
    exit 1
}

set HOST [lindex $argv 0]
set USER_PORT "gpon-onu_[lindex $argv 1]"
set DELAY 1
set timeout 10

# Если нужно, можно захардкодить: set USER "admin"
set USER $env(USER)
set PASS $env(PASS)

spawn telnet $HOST

expect {
    "Username:" { send "$USER\r"; exp_continue }
    "Password:" { send "$PASS\r" }
    timeout { puts "Нет ответа по таймауту"; exit 1 }
}

expect -re {[#>]$}

# Список команд
set commands [list \
    "show gpon onu detail-info $USER_PORT" \
    "show pon power attenuation $USER_PORT" \
    "show mac-real-time gpon onu $USER_PORT" \
    "show gpon remote-onu interface eth $USER_PORT" \
    "show gpon remote-onu interface video-ani $USER_PORT" \
]

foreach cmd $commands {
    send "$cmd\r"
    expect -re {[#>]$}
    sleep $DELAY
}

interact
